### ISSUE TITLE
LVGL - error: 'LV_SCR_LOAD_ANIM_FADE_IN' undeclared

### ISSUE THREAD

**Issue by rtek1000** [eez-open/studio#815]
**Describe the bug**
Hello, first of all, I would like to congratulate everyone for the great service you have done, I was already impressed with the LVGL platform. But EEZ-studio impressed me even more.

I just created the first project for LVGL, and when trying to compile it there was the first error in the src/ui file created by EEZ-studio. I believe it is because I am using the current version of LVGL v9.3.0 which already has differences with LVGL version v9.2.0. I believe it is not possible to have only one "9.x" option, but perhaps it would have to have "9.3", "9.4", "9.5" etc  (because each released version has differences in syntax, I noticed this when I migrated from 8.3.3 to 9.2.0, then had to migrate to 9.3.0).

`/libraries/ui/ui.c:44:30: error: 'LV_SCR_LOAD_ANIM_FADE_IN' undeclared (first use in this function); did you mean 'LV_SCREEN_LOAD_ANIM_FADE_IN'?`

**To Reproduce**

1- Create a project for LVGL 9.x
2- Configure the Arduino IDE preferences to use the library
3- Place the files generated by EEZ-studio in the "livraria/ui" folder
4- Open sketch ui.ino (ui folder)
5- Compile the ui.ino file (Arduino IDE: Verify/Upload)

Ref.: https://github.com/WhiteBr0wnie-24/EEZ-Studio-Arduino-Starter (LVGL v8.3.0)

Updated for LVGL 9.3.0:
https://github.com/rtek1000/EEZ-Studio-Arduino-Starter/tree/main/LVGL_v9.3.0

**Expected behavior**
It would be great if the code generated by EEZ-studio didn't need to be edited manually.

**Screenshots**

**Desktop (please complete the following information):**
Arduino IDE 2.3.4

** LVGL version (if used)**
9.3.0

**Additional context**

**Disclaimer**
_Please take into account that the tasks reported here will be processed by the Envox team according to the best effort principle, so adjust your expectations accordingly. However, if you want a more prompt and high-quality response as well as direct contact with technical support, you can choose one of our [Support plans](https://www.envox.eu/support-plans/)._

**Comment by rtek1000** [comment]
Another thing I noticed is about the location of the <lvgl.h> reference.

The example available in LVGL has <lvgl.h>, but the files generated by EEZ-studio have <lvgl/lvgl.h>. And this also causes error, for every file generated by EEZ-studio.

```C++
/*Using LVGL with Arduino requires some extra steps:
 *Be sure to read the docs here: https://docs.lvgl.io/master/integration/framework/arduino.html  */

#include <lvgl.h>

#if LV_USE_TFT_ESPI
#include <TFT_eSPI.h>
#endif
```
https://github.com/lvgl/lvgl/blob/master/examples/arduino/LVGL_Arduino/LVGL_Arduino.ino


EEZ-studio /library/ui/fileX
```C++
#ifndef EEZ_LVGL_UI_EVENTS_H
#define EEZ_LVGL_UI_EVENTS_H

#include <lvgl/lvgl.h>

#ifdef __cplusplus
extern "C" {
```

**Comment by mvladic** [comment]
> /libraries/ui/ui.c:44:30: error: 'LV_SCR_LOAD_ANIM_FADE_IN' undeclared (first use in this function); did you mean 'LV_SCREEN_LOAD_ANIM_FADE_IN'?

LVGL indeed changed `LV_SCR_LOAD_ANIM_FADE_IN` to `LV_SCREEN_LOAD_ANIM_FADE_IN`, but they still have a definition for the LV_SCR_LOAD_ANIM_FADE_IN in [lv_api_map_v9.2.h](https://github.com/lvgl/lvgl/blob/master/src/lv_api_map_v9_2.h#L43). This file is normally included unless user explicitly defines `LV_DISABLE_API_MAPPING`.

You can either undefine LV_DISABLE_API_MAPPING or change `LV_SCR_LOAD_ANIM_FADE_IN` to `LV_SCREEN_LOAD_ANIM_FADE_IN` here:

<img width="1083" height="833" alt="Image" src="https://github.com/user-attachments/assets/066511e7-ac5d-4db2-8910-2b79ee34a945" />

**Comment by mvladic** [comment]
> Another thing I noticed is about the location of the <lvgl.h> reference.
The example available in LVGL has <lvgl.h>, but the files generated by EEZ-studio have <lvgl/lvgl.h>. And this also causes error, for every file generated by EEZ-studio.

You can change LVGL include location here:

<img width="1097" height="362" alt="Image" src="https://github.com/user-attachments/assets/1ead377b-956c-4887-b013-7073f3f2632d" />
