### ISSUE TITLE
[LVGL] 0.23 compiling error - `<src/lvgl_private.h>` missing

### ISSUE THREAD

**Issue by samloops** [eez-open/studio#770]
**Describe the bug**

Upgrading from V 0.22 to 0.23 introduces code in eez-flow.h at approximately line 20:
 
  #if LVGL_VERSION_MAJOR > 9 || (LVGL_VERSION_MAJOR == 9 && LVGL_VERSION_MINOR > 1)
  #include <src/lvgl_private.h>
  #endif

In Arduino IDE, throws compiling error regarding missing file:

Alternatives for src/lvgl_private.h: []
ResolveLibrary(src/lvgl_private.h)
  -> candidates: []
In file included from /home/sam/eez-projects-lvgl-9x/Thermostat-Project-Master/Thermostat-ESPNOW/ui.h:6,
                 from /home/sam/eez-projects-lvgl-9x/Thermostat-Project-Master/Thermostat-ESPNOW/Thermostat-ESPNOW.ino:15:
/home/sam/eez-projects-lvgl-9x/Thermostat-Project-Master/Thermostat-ESPNOW/eez-flow.h:21:10: fatal error: src/lvgl_private.h: No such file or directory
   21 | #include <src/lvgl_private.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

**To Reproduce**

1) Upgrade from 0.22 to 0.23
2) Open a project in eez-open that had been previously built with 0.22 and rebuild in 0.23
3) Save and compile with Arduido IDE, using same procedure as before  

**Expected behavior**

Error-free compilation

**Desktop (please complete the following information):**

Release Linux Mint 22.1 Xia 64-bit
Kernel Linux 6.8.0-55-generic x86_64

** LVGL version (if used)**

9.2.0

**Additional context**

Rolling back to 0.22 and rebuilding project fixes error.
