### ISSUE TITLE
[LVGL] Window widget doesn't compiles on LVGL 8.4

### ISSUE THREAD

**Issue by Danixu** [eez-open/studio#1006]
**Describe the bug**
When adding a Window widget into my project it doesn't compiles when using the Full Simulation. Also it looks like maybe there are missing configurations like the header height (related with the error), and the preview also doesn't show any header.

**To Reproduce**
1. Create a new LVGL 8.4 project
2. Add a Window widget
3. Press the Full Sim button

**Expected behavior**
The project must compiles to see the simulation. For sure the final compilation will fail too.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Ubuntu 26.04 using the Appimage
- Version 0.27.1

**LVGL version (if used)**
- 8.4.0

**Additional context**
It seems to be a bug related with the LVGL version. The LVGL 9.X versions has changed the way that the widget is created and managed:
https://lvgl.io/docs/open/8.4/widgets/extra/win.html
https://lvgl.io/docs/open/9.0/API/widgets/win/lv_win.html

Error message:
```
/project/src/screens.c:33:53: error: too few arguments to function call, expected 2, have 1
33 | lv_
obj_t *obj = lv_win_create(parent_obj);
| ~~~~~~~~~~~~~ ^
/project/lvgl/src/extra/widgets/win/lv_win.h:35:12: note: 'lv_win_create' declared here
35 | lv_obj_t * lv_win_create(lv_obj_t * parent, lv_coord_t header_height);
| ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/index.dir/build.make:107: CMakeFiles/index.dir/src/screens.c.o] Error 1
```

**Comment by mvladic** [comment]
Fixed. Thanks!

**Comment by Danixu** [comment]
Great!!, thanks!!. I'll try to run the master version for test it.
